language: emacs

env:
  - "CHECK_TARGET=check-core  LISP=sbcl  EMACS=emacs24"
  - "CHECK_TARGET=check-core  LISP=cmucl EMACS=emacs24"
  - "CHECK_TARGET=check-core  LISP=ccl   EMACS=emacs24"
  - "CHECK_TARGET=check-fancy LISP=sbcl  EMACS=emacs24"
  - "CHECK_TARGET=check-fancy LISP=cmucl EMACS=emacs24"
  - "CHECK_TARGET=check-fancy LISP=ccl   EMACS=emacs24"

  # also, for emacs24/sbcl test some more contribs in isolation
  - "CHECK_TARGET=check-mrepl LISP=sbcl EMACS=emacs24"
  - "CHECK_TARGET=check-indentation LISP=sbcl EMACS=emacs24"

install:
  - curl https://raw.githubusercontent.com/capitaomorte/cl-travis/master/install.sh | bash
  - if [ "$EMACS" = "emacs24" ]; then
        SOURCE=http://mirrors.kernel.org/ubuntu/pool/main/e/emacs24;
        curl -O $SOURCE/emacs24-nox_24.3+1-2ubuntu1_i386.deb;
        curl -O $SOURCE/emacs24-el_24.3+1-2ubuntu1_all.deb;
        curl -O $SOURCE/emacs24-common_24.3+1-2ubuntu1_all.deb;
        curl -O $SOURCE/emacs24-bin-common_24.3+1-2ubuntu1_i386.deb;
        dpkg -x emacs24-nox_24.3+1-2ubuntu1_i386.deb .;
        dpkg -x emacs24-el_24.3+1-2ubuntu1_all.deb .;
        dpkg -x emacs24-common_24.3+1-2ubuntu1_all.deb .;
        dpkg -x emacs24-bin-common_24.3+1-2ubuntu1_i386.deb .;
    fi

script:
  - export PATH=./usr/bin:$PATH && make LISP=$LISP EMACS=$EMACS $CHECK_TARGET
