version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2
        environment:
          LISP: sbcl-bin/1.2.14
          TARGET: check-core
      - image: circleci/ruby:2
        environment:
          LISP: ccl-bin
          TARGET: check-fancy
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Install emacs
          # Installs under HOME
          command:  |
            wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
            make -f emacs-travis.mk install_emacs
      - run:
          name: Install Roswell
          command:  |
            export ROSWELL_INSTALL_DIR=~/.roswell
            mkdir -p $ROSWELL_INSTALL_DIR
            export PATH=$ROSWELL_INSTALL_DIR/bin:$PATH
            curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
      - run:
          name: Check core
          command: |
            make LISP="$HOME/.roswell/bin/ros run -L sbcl-bin/1.2.14" EMACS="$HOME/emacs/25.3/src/emacs" $TARGET
            
      
          
